#!/usr/bin/env python3
"""Roll dice from the command line
    
    Roll N M-sided die where
        N: number of dice to roll (implicitly N=1 if omitted)
        M: the maximum value on the die (must be at least 1)
     e.g.:   'd6' -> roll one six-sided die
           '3d20' -> roll three twenty-sided dice
       'd2 d3 d4' -> roll a two-, three-, and four-sided die
"""

import random
import sys

from argparse import ArgumentError

def die(value):
    """Parse a die string of the form (N)dM int a tuple of integers where:
        N: an optional number of dice (implicitly N=1 if omitted)
        M: the number of sides on the die
    
    E.g.:
        parse('d6') -> (1, 6)
        parse('1d6') -> (1, 6)
        parse('2d4') -> (2, 4)
    """
    try:
        n, m = value.lower().split('d', 1)
        return int(n or 1), int(m)
    except:
        raise ArgumentError('invalid die string')

def roll(n, m):
    """Generate n random integers in the range [1..m]"""
    for i in range(n):
        yield random.randint(1, m)

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description=__doc__
    )
    parser.add_argument(
        'dice',
        nargs='+',
        type=die,
        metavar='[N]dM',
        help='roll N M-sided dice',
    )
    args = parser.parse_args()
    for n, m in args.dice:
        print('{}d{}\t{}'.format(n, m, sum(roll(n, m))))
