#!/usr/bin/env python
"""Roll dice from the command line"""

import random
import sys

def usage():
    """print usage instructions to stderr"""
    print >> sys.stderr, __doc__ + \
    """
    usage: ./rolldice (n)dm [(n)dm ...]
        n: number of dice to roll (n = 1 if omitted)
        m: the maximum value on the die (must be at least 1)
     e.g.:   'd6' -> roll single six-sided die
           '3d20' -> roll three twenty-sided dice
       'd2 d3 d4' -> roll a two-, three-, and four-sided die
    """

def parse(die):
    """parse('1d6') -> (1, 6)"""
    n, d = die.lower().split('d')
    return map(int, (n or 1, d))

def roll(n, d):
    """generate n random integers in the range [1..d]"""
    for i in range(n):
        yield random.randint(1, d)

def main(dice):
    """parse a list of dice and print each die interpretation with its result"""
    for die in dice:
        n, d = parse(die)
        print '{}d{}\t{}'.format(n, d, sum(roll(n, d)))

if __name__ == '__main__':
    script, dice = sys.argv[0], sys.argv[1:]
    if (not dice) or dice[0].lower() in ('-h', '--help'):
        usage()
        sys.exit(0)
    else:
        main(dice)
